// ################################################################ 
//  This file has been generated by the hashspace compiler          
//  Direct MODIFICATIONS WILL BE LOST when the file is recompiled!  
// ################################################################ 

var hsp=require("hsp/rt");
var $set=require("hsp/$set");


var message = require("hsp/rt").template(["msg"], function(n){
  return [n.$text(0,[" "]),n.elt("div",0,0,{"selectstart":"return false"},[n.elt("a",{e1:[4,1,toggleUrgency]},0,{"click":1},[n.$text(0,["Change Urgency"])]),n.$text(0,[" -  "]),n.elt("a",{e1:[4,1,setCategory,0,"personal"]},0,{"click":1},[n.$text(0,["Set \"Personal\""])]),n.$text(0,[" -  "]),n.elt("a",{e1:[4,1,setCategory,0,"professional"]},0,{"click":1},[n.$text(0,["Set \"Professional\""])]),n.elt("div",{e1:[6,function(a0,a1) {return ["msg",(((a0 === 1))? ''+"urgent":''),a1].join(' ');},2,3],e2:[1,2,"msg","urgency"],e3:[1,2,"msg","category"]},{"class":["",1]},0,[n.$text({e1:[1,2,"msg","text"]},["Message: ",1," "])]),n.elt("div",0,{"class":"note"},0,[n.$text({e1:[6,function(a0,a1) {return ["msg",(((a0 === 1))? ''+"urgent":''),a1].join(' ');},2,3],e2:[1,2,"msg","urgency"],e3:[1,2,"msg","category"]},["Class value: \"",1,"\" "])])])];
});


var msg={
    text:"Hello World",
    urgency:0
}

function toggleUrgency() {
    $set(msg,"urgency",msg.urgency? 0 : 1);
}

function setCategory(cat) {
    $set(msg,"category",cat);
}

// display the template in the #output div
message(msg).render("output");

