// ################################################################ 
//  This file has been generated by the hashspace compiler          
//  Direct MODIFICATIONS WILL BE LOST when the file is recompiled!  
// ################################################################ 

var hsp=require("hsp/rt");
var gestures = require("hsp/rt").template(["msgList"], function(n){
  return [n.elt("div",{e1:[4,1,addMsg,1,2],e2:[0,1,"event"],e3:[4,1,addMsg,1,4],e4:[0,1,"event"],e5:[4,1,addMsg,1,6],e6:[0,1,"event"]},{"class":"touchboard","style":"height:200px; background: #27AAFC;text-align:center;"},{"tap":1,"tapstart":3,"tapcancel":5},[n.elt("h1",0,0,0,[n.$text(0,["TOUCH ME"])])]),n.elt("div",0,{"class":"msglist"},0,[n.$foreach({e1:[1,1,"msgList"]},"msg_key","msg",0,1,[n.elt("div",0,0,0,[n.$text({e1:[1,1,"msg"]},["",1])])]),n.$text(0,[" "])])];
});


var eventLog = [];

function addMsg(evt) {
	eventLog.push(evt.duration + "ms - " + evt.type + " from " + evt.target.tagName);
}

// display the template in the #output div
gestures(eventLog).render("output");
