// ################################################################ 
//  This file has been generated by the hashspace compiler          
//  Direct MODIFICATIONS WILL BE LOST when the file is recompiled!  
// ################################################################ 

var hsp=require("hsp/rt");
var $set=require("hsp/$set");


var people = require("hsp/rt").template(["d"], function(n){
  return [n.elt("div",0,{"class":"msg"},0,[n.$text(0,["Click on a person to see more details:"])]),n.elt("ul",0,0,0,[n.$foreach({e1:[1,2,"d","people"]},"p_key","p",0,1,[n.elt("li",{e1:[6,function(a0,a1) {return [((a0)? ''+"details":''),(((a1 === "Bart"))? ''+"special":'')].join(' ');},2,3],e2:[1,2,"p","showdetails"],e3:[1,2,"p","name"],e4:[4,1,toggleDetails,1,5],e5:[1,1,"p"]},{"class":["",1]},{"click":4},[n.$text({e1:[1,2,"p","name"]},["",1," "]),n.$if({e1:[1,2,"p","showdetails"]},1,[n.$text({e1:[1,2,"p","age"]},[": ",1," years old"])])])]),n.$text(0,[" "])]),n.elt("div",0,{"class":"msg"},0,[n.$text({e1:[1,3,"d","people","length"]},["Number of people in the list: ",1," "])])];
});


function toggleDetails(person) {
    $set(person,"showdetails",!person.showdetails);
}

var d={
    people: [
        {name:"Homer", age:38},
        {name:"Marge", age:38},
        {name:"Bart", age:10},
        {name:"Lisa", age:8},
        {name:"Maggie", age:1}
    ]
}

// display the template in the #output div
people(d).render("output");


