// ################################################################ 
//  This file has been generated by the hashspace compiler          
//  Direct MODIFICATIONS WILL BE LOST when the file is recompiled!  
// ################################################################ 

var hsp=require("hsp/rt");


var mainLayout =exports.mainLayout = require("hsp/rt").template(["data","ctl"], function(n){
  return [n.elt("div",0,{"class":"main"},0,[n.elt("div",0,{"class":"header"},0,[n.elt("div",0,{"class":"hashspace"},0,[n.elt("span",0,{"class":"hash"},0,[n.$text(0,["#"])]),n.elt("span",0,{"class":"name"},0,[n.$text(0,["hashspace"])])])]),n.elt("div",{e1:[3,2,"ctl","hideSampleList"]},{"class":"playground"},{"mouseover":1},[n.elt("div",0,{"class":"descriptionContainer"},0,[n.$insert({e1:[4,1,sampleList,1,2,1,3],e2:[1,1,"data"],e3:[1,1,"ctl"]},1),n.$text(0,["   "]),n.elt("div",0,{"id":"description"},0,[n.$text(0,[" "])])]),n.$text(0,[" "]),n.elt("div",0,{"class":"editorContainer"},0,[n.elt("div",0,{"class":"editorTabs"},0,[n.$foreach({e1:[1,2,"data","files"]},"file_key","file",0,1,[n.$text({e1:[1,2,"file","src"]},["",1," "])]),n.$text(0,[" "])]),n.$text(0,["  "]),n.elt("div",0,{"id":"playgroundEditor"},0)])])])];
});



var sampleList = require("hsp/rt").template(["data","ctl"], function(n){
  return [n.$text(0,[" "]),n.elt("div",{e1:[3,2,"ctl","showSampleList",1,2],e2:[0,1,"event"]},{"class":"sampleTitle"},{"mouseover":1},[n.elt("a",0,0,0,[n.$text({e1:[6,function(a0) {return (a0 + 1);},2],e2:[1,2,"data","sampleIndex"]},["Sample #",1,":"])]),n.$text({e1:[1,2,"data","sampleTitle"]},[" ",1,"  "]),n.$if({e1:[1,2,"data","isSampleListVisible"]},1,[n.elt("div",0,{"class":"sampleList"},0,[n.$foreach({e1:[1,2,"data","samples"]},"idx","sample",0,1,[n.elt("div",{e1:[3,2,"ctl","loadSample",1,2],e2:[1,1,"idx"]},{"class":"item"},{"click":1},[n.$text({e1:[6,function(a0) {return (a0 + 1);},2],e2:[1,1,"idx"],e3:[1,2,"sample","title"]},["",1,". ",3])])]),n.$text(0,[" "])])])])];
});



var errorList =exports.errorList = require("hsp/rt").template(["errors"], function(n){
  return [n.elt("div",0,{"class":"errorlist"},0,[n.elt("ul",0,0,0,[n.$foreach({e1:[1,1,"errors"]},"err_key","err",0,1,[n.elt("li",0,0,0,[n.elt("span",0,{"class":"description"},0,[n.$text({e1:[1,2,"err","description"]},[" ",1," "])]),n.$if({e1:[1,2,"err","line"]},1,[n.$text({e1:[1,2,"err","line"],e2:[1,2,"err","column"]},["line: ",1,", column: ",2])]),n.$if({e1:[1,2,"err","code"]},1,[n.elt("div",0,{"class":"code"},0,[n.$text(0,[">> code: "]),n.elt("span",0,{"class":"code"},0,[n.$text({e1:[1,2,"err","code"]},["",1])])])])])]),n.$text(0,[" "])])])];
});


